services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - back
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: development
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app
