services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - back
      - db
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: development
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokepoke

  db:
    image: postgres:14.15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokepoke
    volumes:
      - pokepokedb:/var/lib/postgresql/data

volumes:
  pokepokedb:
