services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development