openapi: '3.0.3'
info:
  title: pokepoke deck
  version: '1.0'
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'health'
  /cards:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      $ref: '#/components/schemas/Card'
  /card:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Card'
      responses:
        '201':
          description: Created
                  
components:
  schemas:
    Card:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'bulbasaur'